# Generated by Django 4.2.6 on 2023-11-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engrais_Aoulouz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(blank=True, choices=[('Ammonitrate', 'Ammonitrate'), ('Sulfat_potasse', 'Sulfat_potasse'), ('MAP', 'MAP'), ('Nitrat_potasse', 'Nitrat_potasse'), ('Calcium', 'Calcium'), ('Complet', 'Complet'), ('Acide', 'Acide'), ('Sequestrine', 'Sequestrine'), ('Uree_46', 'Uree_46'), ('Kimia', 'Kimia')], max_length=50, null=True)),
                ('stock', models.CharField(blank=True, max_length=100)),
                ('mesure', models.CharField(blank=True, choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engrais_berhil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(blank=True, choices=[('Ammonitrate', 'Ammonitrate'), ('Sulfat_potasse', 'Sulfat_potasse'), ('MAP', 'MAP'), ('Nitrat_potasse', 'Nitrat_potasse'), ('Calcium', 'Calcium'), ('Complet', 'Complet'), ('Acide', 'Acide'), ('Sequestrine', 'Sequestrine'), ('Uree_46', 'Uree_46'), ('Kimia', 'Kimia')], max_length=50, null=True)),
                ('stock', models.CharField(blank=True, max_length=100)),
                ('mesure', models.CharField(blank=True, choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Engrais_Mariem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('categorie', models.CharField(blank=True, choices=[('Ammonitrate', 'Ammonitrate'), ('Sulfat_potasse', 'Sulfat_potasse'), ('MAP', 'MAP'), ('Nitrat_potasse', 'Nitrat_potasse'), ('Calcium', 'Calcium'), ('Complet', 'Complet'), ('Acide', 'Acide'), ('Sequestrine', 'Sequestrine'), ('Uree_46', 'Uree_46'), ('Kimia', 'Kimia')], max_length=50, null=True)),
                ('stock', models.CharField(blank=True, max_length=100)),
                ('mesure', models.CharField(blank=True, choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mouvement_caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('Zone', models.CharField(blank=True, choices=[('Hwara', 'Hwara'), ('Od_berhil', 'Od_berhil'), ('Aoulouz', 'Aoulouz')], max_length=50, null=True)),
                ('Verger', models.CharField(choices=[('436', '436'), ('4660', '4660'), ('3434', '3434'), ('2805', '2805'), ('2200', '2200'), ('2453', '2453'), ('1286', '1286'), ('2463', '2463'), ('774', '774'), ('1574', '1574'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('NBR_caisses_Entrée', models.IntegerField(default=0)),
                ('Bon_caisserie', models.CharField(blank=True, max_length=50)),
                ('Véhicule_entré', models.CharField(blank=True, max_length=50)),
                ('NBR_caisses_Sortie', models.IntegerField(default=0)),
                ('Bon_livraison', models.CharField(blank=True, max_length=50)),
                ('Véhicule_sorti', models.CharField(blank=True, max_length=50)),
                ('Varieté', models.CharField(choices=[('Nules', 'Nules'), ('Bruno', 'Bruno'), ('Orograndé', 'Orograndé'), ('Clémentine', 'Clémentine'), ('Nour', 'Nour'), ('Laarache', 'Laarache'), ('Nadorcott', 'Nadorcott'), ('Navel', 'Navel'), ('Maroc_late', 'Maroc_late'), ('Salustiana', 'Salustiana'), ('Citron', 'Citron'), ('W.sanguine', 'W.sanguine'), ('Pomelo', 'Pomelo')], max_length=50)),
                ('Poids', models.IntegerField(default=0)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide_Aoulouz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movento', 'Movento'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre'), ('Nissorun', 'Nissorun'), ('Tridicorp Jaguar', 'Tridicorp Jaguar'), ('Twinteck zin+mn', 'Twinteck zin+mn'), ('Fengib', 'Fengib'), ('Ariatox', 'Ariatox'), ('Kimia', 'Kimia'), ('Proximo', 'Proximo')], max_length=50, null=True)),
                ('groupe', models.CharField(blank=True, choices=[('Pesticide', 'Pesticide'), ('Fongicide', 'Fongicide'), ('Herbicide', 'Herbicide'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('stock', models.CharField(blank=True, max_length=100)),
                ('mesure', models.CharField(blank=True, choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pesticide_berhil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movento', 'Movento'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre'), ('Nissorun', 'Nissorun'), ('Tridicorp Jaguar', 'Tridicorp Jaguar'), ('Twinteck zin+mn', 'Twinteck zin+mn'), ('Fengib', 'Fengib'), ('Ariatox', 'Ariatox'), ('Kimia', 'Kimia'), ('Proximo', 'Proximo')], max_length=50, null=True)),
                ('groupe', models.CharField(blank=True, choices=[('Pesticide', 'Pesticide'), ('Fongicide', 'Fongicide'), ('Herbicide', 'Herbicide'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('stock', models.CharField(blank=True, max_length=100)),
                ('mesure', models.CharField(blank=True, choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pesticide_Mariem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(blank=True, choices=[('Karaté', 'Karaté'), ('Blouz', 'Blouz'), ('AG3', 'AG3'), ('Agrale', 'Agrale'), ('Coperniko', 'Coperniko'), ('Confidor', 'Confidor'), ('Valmec', 'Valmec'), ('Joker', 'Joker'), ('Pixel', 'Pixel'), ('Coperide', 'Coperide'), ('Mospelan', 'Mospelan'), ('Rodo', 'Rodo'), ('Fozika', 'Fozika'), ('Movento', 'Movento'), ('enfidor-speed', 'enfidor-speed'), ('Magnome', 'Magnome'), ('Samba', 'Samba'), ('Fozika_ca', 'Fozika_ca'), ('Soufre', 'Soufre'), ('Nissorun', 'Nissorun'), ('Tridicorp Jaguar', 'Tridicorp Jaguar'), ('Twinteck zin+mn', 'Twinteck zin+mn'), ('Fengib', 'Fengib'), ('Ariatox', 'Ariatox'), ('Kimia', 'Kimia'), ('Proximo', 'Proximo')], max_length=50, null=True)),
                ('groupe', models.CharField(blank=True, choices=[('Pesticide', 'Pesticide'), ('Fongicide', 'Fongicide'), ('Herbicide', 'Herbicide'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('stock', models.CharField(blank=True, max_length=100)),
                ('mesure', models.CharField(blank=True, choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mouvement_1286',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_1574',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_2200',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_2453',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_2463',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_2805',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_3434',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_436',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_4660',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='Mouvement_774',
            fields=[
                ('mouvement_caisse_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='paie.mouvement_caisse')),
            ],
            bases=('paie.mouvement_caisse',),
        ),
        migrations.CreateModel(
            name='caisse_Mariem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('recette', models.CharField(blank=True, max_length=100)),
                ('cumul_recette', models.CharField(blank=True, max_length=100)),
                ('depense', models.CharField(blank=True, max_length=100)),
                ('cumul_depense', models.CharField(blank=True, max_length=100)),
                ('solde', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='caisse_berhil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100)),
                ('recette', models.CharField(blank=True, max_length=100)),
                ('cumul_recette', models.CharField(blank=True, max_length=100)),
                ('depense', models.CharField(blank=True, max_length=100)),
                ('cumul_depense', models.CharField(blank=True, max_length=100)),
                ('solde', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100)),
                ('titre', models.CharField(blank=True, choices=[('Ouled_berhil', 'Ouled_berhil'), ('Ouled_drisse', 'Ouled_drisse'), ('Aoulouz', 'Aoulouz'), ('Mariem', 'Mariem'), ('Maryem2', 'Maryem2'), ('Plombier', 'Plombier'), ('Zbirate', 'Zbirate'), ('Glidi', 'Glidi'), ('Ben_mbarek', 'Ben_mbarek'), ('Raisin', 'Raisin'), ('Bananier1', 'Bananier1'), ('Bananier2', 'Bananier2')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('times', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Achat_zbirate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_rgaigue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_raisin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_murcott',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_Maryem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_Mariem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_lglidi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_drisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_berhil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_benmbark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_bananier2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_bananier1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achat_Aoulouz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(blank=True, max_length=50, null=True)),
                ('desg', models.CharField(max_length=100)),
                ('Qté', models.FloatField(default=0)),
                ('pu', models.FloatField(default=0)),
                ('pt', models.FloatField(blank=True, default=None, null=True)),
                ('unite', models.CharField(choices=[('KG', 'KG'), ('Litre', 'Litre'), ('Sachet', 'Sachet'), ('Autre', 'Autre')], max_length=50, null=True)),
                ('Observation', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
